extends: .github
shared:
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash
  CheckRuns: &CheckRuns
    - check-success=linters
    - check-success=test-junit
    - check-success=test-scopes
    - check-success=autodoc


scopes:
  source:
    files:
      # Used by .github/workflow/ci.yml to test the action
      everything: {}

merge_queue:
  max_parallel_checks: 5

queue_rules:
  - name: automated updates
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base = main
      - or:
          - author = mergify-ci-bot
          - author = renovate[bot]
          - author = dependabot[bot]
    merge_method: merge
    merge_conditions:
      - and: *CheckRuns
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template:
    queue_branch_merge_method: fast-forward


  - name: default
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base = main
    merge_conditions:
      - and: *CheckRuns

pull_request_rules:
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -author=renovate[bot]
      - -author=mergify-ci-bot
      - -merged
      - -closed
      - check-success=all-greens
      - "#changes-requested-reviews-by=0"
      - review-requested!=@devs
      - and:
          - not:
              or: &DefaultReviewCond
                - "#approved-reviews-by>=1"
                - author = dependabot[bot]
                - author = renovate[bot]
                - author = mergify-ci-bot
    actions:
      request_reviews:
        teams:
          - devs

merge_protections:
  - name: 🤖 Continuous Integration
    if: []
    success_conditions:
      - and: *CheckRuns

  - name: 👀 Review Requirements
    if: []
    success_conditions:
      - or: *DefaultReviewCond

merge_protections_settings:
  reporting_method: deployments
